Server:
  port: 51001

spring:
  application:
    name: tu-wms-inventorying
  datasource:
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
    url: jdbc:mysql://172.16.200.42:3306/testdb?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: dev_w
    password: devw@234
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-init-sqls: SET NAMES utf8mb4
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

mybatis:
  mapperLocations: classpath*:*Mapper.xml
  config-location: classpath:mybatis.xml

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  wms-inventorying-service:
    name: ${spring.application.name}

eureka:
  instance:
    perfer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: ${spring.cloud.client.ip-address}
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://admin:a0222943@localhost:10001/eureka/
  server:
    enable-self-preservation: false


management:
  endpoint:
    restart:
      enabled: true
    pause:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


